# Generated by Django 4.1.7 on 2023-03-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("pokedex_id", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("weight", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=100)),
                ("secondary_type", models.CharField(max_length=100)),
                ("hp", models.PositiveIntegerField()),
                ("attack", models.PositiveIntegerField()),
                ("defense", models.PositiveIntegerField()),
                ("sp_atk", models.PositiveIntegerField()),
                ("sp_def", models.PositiveIntegerField()),
                ("speed", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Pokemon",
                "verbose_name_plural": "Pokemon",
                "ordering": ("name",),
            },
        ),
    ]
